apiVersion: apps/v1
kind: Deployment
metadata:
  name: futurekawa-front
  namespace: futurekawa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: futurekawa-front
  template:
    metadata:
      labels:
        app: futurekawa-front
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: front
          image: ghcr.io/plusdefritesalacantine/front_futurekawa:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"